# Generated by Django 4.2.6 on 2024-07-19 03:37

import apps.accounts.utils
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=apps.accounts.utils.profile_image_storage, validators=[common.validators.validate_image_extension, common.validators.validate_max_file_size]),
        ),
    ]
