# Generated by Django 4.2.6 on 2024-07-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
